// ============================================================
// Intelligaia AI UX Pattern Library — pattern.js
// 3-column detail page · sidebar + content + on-this-page TOC
// ============================================================
(function () {
  const L = window.LIBRARY;
  const $ = (s, r = document) => r.querySelector(s);
  const $$ = (s, r = document) => Array.from(r.querySelectorAll(s));
  const esc = (s) => String(s ?? "").replace(/[&<>"']/g, c => ({ "&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;" }[c]));
  const valueLabel = { crit: "Critical", high: "High", med: "Medium", low: "Low" };

  // ───────────────────────────────────────────────────────
  // Visual mocks (shared across pages — kept rich on detail)
  // ───────────────────────────────────────────────────────
  const visuals = {
    disclosure: () => `
      <div class="mock mock--lg" style="width:80%">
        <div style="display:flex;align-items:center;gap:10px">
          <span style="display:inline-flex;align-items:center;gap:4px;padding:3px 8px;border-radius:5px;background:var(--ink-950);color:var(--ink-0);font-size:10px;font-weight:600;letter-spacing:0.06em">AI</span>
          <span style="font-size:13px;color:var(--fg-mid)">Intelligaia agent</span>
          <span style="margin-left:auto;font-size:11px;color:var(--fg-muted)">just now</span>
        </div>
        <div style="margin-top:10px;font-size:13px;line-height:20px;color:var(--fg)">Here's a summary of your Q2 numbers — generated by the assistant. Verify before sharing externally.</div>
      </div>`,
    consent: () => `
      <div class="mock mock--lg" style="width:70%;padding:20px">
        <div style="font-size:15px;font-weight:600">Allow data to improve the assistant?</div>
        <div style="font-size:12px;color:var(--fg-muted);margin-top:6px;line-height:17px">Inputs never leave your tenant. Toggle anytime in Settings.</div>
        <div style="display:flex;gap:8px;margin-top:14px">
          <span style="padding:7px 16px;border-radius:9999px;background:var(--ink-950);color:var(--ink-0);font-size:12px;font-weight:500">Allow</span>
          <span style="padding:7px 16px;border-radius:9999px;border:1px solid var(--border);color:var(--fg-mid);font-size:12px;font-weight:500">Not now</span>
        </div>
      </div>`,
    caveat: () => `
      <div class="mock mock--lg" style="width:74%">
        <div style="height:34px;border:1px solid var(--border);border-radius:8px;background:var(--ink-25);display:flex;align-items:center;padding:0 12px;font-size:12px;color:var(--fg-muted)">Ask anything…</div>
        <div style="margin-top:8px;font-size:11px;color:var(--fg-muted);display:flex;gap:6px;align-items:center">
          <svg width="11" height="11" viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="9" stroke="currentColor" stroke-width="2"/><path d="M12 8v5M12 16h.01" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg>
          The assistant may make mistakes. Verify important info.
        </div>
      </div>`,
    avatar: () => `
      <div class="mock mock--lg" style="display:flex;align-items:center;gap:14px;width:auto">
        <span style="width:44px;height:44px;border-radius:50%;background:linear-gradient(135deg,var(--ink-950),var(--ink-600));color:var(--ink-0);display:grid;place-items:center;font-size:16px;font-weight:600">i</span>
        <div>
          <div style="font-size:14px;font-weight:600">Intelligaia</div>
          <div style="font-size:12px;color:var(--fg-muted)">agent · online</div>
        </div>
      </div>`,
    name: () => `
      <div class="mock mock--lg" style="display:flex;align-items:center;gap:10px;border-radius:9999px;width:auto;padding:10px 16px">
        <span style="width:22px;height:22px;border-radius:50%;background:var(--ink-950);color:var(--ink-0);display:grid;place-items:center;font-size:11px;font-weight:600">i</span>
        <span style="font-size:13px">Aria is drafting</span>
        <span style="display:flex;gap:3px"><span style="width:5px;height:5px;border-radius:50%;background:var(--fg-mid);animation:pulse 1.4s infinite"></span><span style="width:5px;height:5px;border-radius:50%;background:var(--fg-mid);animation:pulse 1.4s infinite 0.2s"></span><span style="width:5px;height:5px;border-radius:50%;background:var(--fg-mid);animation:pulse 1.4s infinite 0.4s"></span></span>
      </div>`,
    personality: () => `
      <div class="mock mock--lg">
        <div style="font-size:13px;line-height:20px;color:var(--fg-alt)">"Here's what I found. Two of these look unusual — I flagged them at the top. Want me to dig in?"</div>
        <div style="font-size:11px;color:var(--fg-muted);font-weight:500;margin-top:10px">Voice · calm · proactive</div>
      </div>`,
    iconography: () => `
      <div class="mock mock--lg" style="display:flex;gap:10px;width:auto;padding:14px">
        <span style="display:inline-flex;align-items:center;gap:8px;padding:8px 14px;border-radius:8px;background:var(--ink-950);color:var(--ink-0);font-size:12px;font-weight:500">
          <svg width="12" height="12" viewBox="0 0 24 24" fill="currentColor"><path d="M12 2l1.4 4.6L18 8l-4.6 1.4L12 14l-1.4-4.6L6 8l4.6-1.4z"/></svg>
          Generate
        </span>
        <span style="display:inline-flex;align-items:center;gap:8px;padding:8px 14px;border-radius:8px;border:1px solid var(--border);color:var(--fg-mid);font-size:12px;font-weight:500">Save</span>
      </div>`,
    color: () => `
      <div class="mock mock--lg" style="border-left:3px solid var(--accent);background:linear-gradient(90deg,var(--accent-ghost),transparent);padding:16px">
        <div style="font-size:14px;line-height:20px;color:var(--fg)">Analysing your Q2 numbers<span style="color:var(--accent);font-weight:600;animation:blink 1s infinite">_</span></div>
        <div style="font-size:11px;color:var(--accent);font-weight:600;margin-top:8px">Streaming</div>
      </div>`,
    gallery: () => `
      <div class="mock mock--lg" style="width:66%;padding:16px">
        <div style="font-size:11px;color:var(--fg-muted);font-weight:600;margin-bottom:10px">Try one</div>
        <div style="display:grid;grid-template-columns:1fr 1fr;gap:8px">
          <div style="height:44px;border-radius:6px;background:linear-gradient(135deg,#fde2e2,#fcd5d5);display:grid;place-items:center;font-size:12px;color:#9f1239;font-weight:600">A</div>
          <div style="height:44px;border-radius:6px;background:linear-gradient(135deg,#dde7ff,#c4d5ff);display:grid;place-items:center;font-size:12px;color:#1d4ed8;font-weight:600">B</div>
          <div style="height:44px;border-radius:6px;background:linear-gradient(135deg,#d1fae5,#a7f3d0);display:grid;place-items:center;font-size:12px;color:#065f46;font-weight:600">C</div>
          <div style="height:44px;border-radius:6px;background:linear-gradient(135deg,#fde68a,#fcd34d);display:grid;place-items:center;font-size:12px;color:#92400e;font-weight:600">D</div>
        </div>
      </div>`,
    templates: () => `
      <div class="mock mock--lg" style="width:74%">
        <div style="font-size:14px;line-height:22px;color:var(--fg-alt)">
          Summarise
          <span style="display:inline-flex;padding:2px 9px;border-radius:5px;border:1px dashed var(--accent);background:var(--accent-ghost);color:var(--accent);font-size:12px;font-weight:500">[meeting]</span>
          in
          <span style="display:inline-flex;padding:2px 9px;border-radius:5px;border:1px dashed var(--accent);background:var(--accent-ghost);color:var(--accent);font-size:12px;font-weight:500">[3 bullets]</span>
          for
          <span style="display:inline-flex;padding:2px 9px;border-radius:5px;border:1px dashed var(--accent);background:var(--accent-ghost);color:var(--accent);font-size:12px;font-weight:500">[execs]</span>.
        </div>
      </div>`,
    nudges: () => `
      <div class="mock mock--lg" style="border:none;box-shadow:none;background:transparent;width:70%">
        <div style="display:flex;align-items:flex-start;gap:12px">
          <div style="width:54px;height:34px;border-radius:8px;background:var(--ink-25);border:1px solid var(--border);flex-shrink:0;margin-top:24px"></div>
          <div style="position:relative;background:var(--ink-950);color:var(--ink-0);padding:10px 14px;border-radius:10px;box-shadow:var(--shadow-3);font-size:12px;line-height:17px;max-width:260px">
            <span style="opacity:0.7">Tip</span> · Try uploading a PDF — the assistant can summarise it.
            <span style="position:absolute;left:-6px;top:18px;width:0;height:0;border-top:6px solid transparent;border-bottom:6px solid transparent;border-right:6px solid var(--ink-950)"></span>
          </div>
        </div>
      </div>`,
    disclaimer: () => `
      <div class="mock mock--lg" style="background:var(--ink-25);width:62%;padding:16px">
        <div style="font-size:13px;font-weight:600;color:var(--fg);margin-bottom:8px">What this can do</div>
        <div style="font-size:12px;color:var(--fg-mid);line-height:18px">• Summarise documents<br/>• Draft replies<br/>• Pull from connected sources</div>
        <div style="font-size:11px;color:var(--fg-muted);margin-top:12px">Knowledge cutoff · Apr 2026</div>
      </div>`,
    placeholder: () => `
      <div style="display:flex;flex-direction:column;gap:10px;align-items:center;color:var(--fg-muted)">
        <svg width="48" height="48" viewBox="0 0 24 24" fill="none"><rect x="3" y="3" width="18" height="18" rx="3" stroke="currentColor" stroke-width="1.5" stroke-dasharray="3 3"/></svg>
        <span style="font-size:13px;font-weight:500">Documentation in progress</span>
      </div>`
  };

  const visualFor = (p) => visuals[p.id] || visuals[p.visual] || visuals.placeholder;

  // ───────────────────────────────────────────────────────
  // Templatized tool-shell wireframes
  // Each shell is a generic representation of an AI-native
  // tool archetype. The `slot` HTML (a variant mock) is
  // injected at the natural location for that archetype.
  // ───────────────────────────────────────────────────────
  // Generic, brand-free labels. Sentence case only.
  const templateMeta = {
    chat:      { label: "Chat interface",       use: "Conversation surfaces" },
    rightrail: { label: "Sidebar assistant",    use: "Workspace co-pilots" },
    creative:  { label: "Canvas tool",          use: "Visual creation" },
    video:     { label: "Timeline editor",      use: "Video and audio" },
    code:      { label: "Code editor",          use: "Developer environments" },
    email:     { label: "Productivity surface", use: "Email and documents" }
  };

  // Reusable bits
  const winBar = `
    <div class="tshell__winbar">
      <span class="tshell__dot" style="background:#ff6058"></span>
      <span class="tshell__dot" style="background:#ffbe2f"></span>
      <span class="tshell__dot" style="background:#2bc940"></span>
      <span class="tshell__urlbar"></span>
    </div>`;

  const templates = {
    chat: (slot) => `
      <div class="tshell tshell--chat">
        ${winBar}
        <div class="tshell__body tshell__body--chat">
          <aside class="tshell__nav">
            <div class="tshell__nav-row tshell__nav-row--active"></div>
            <div class="tshell__nav-row"></div>
            <div class="tshell__nav-row"></div>
            <div class="tshell__nav-row"></div>
            <div class="tshell__nav-row tshell__nav-row--short"></div>
          </aside>
          <main class="tshell__main">
            <div class="tshell__msg tshell__msg--user">
              <div class="tshell__msg-bubble tshell__msg-bubble--user">
                <span class="tshell__skel" style="width:140px"></span>
                <span class="tshell__skel" style="width:90px"></span>
              </div>
            </div>
            <div class="tshell__msg tshell__msg--ai">
              <div class="tshell__msg-bubble tshell__msg-bubble--ai tshell__slot">${slot}</div>
            </div>
            <div class="tshell__composer">
              <span class="tshell__composer-placeholder">Message Aria…</span>
              <span class="tshell__composer-send"></span>
            </div>
          </main>
        </div>
      </div>`,

    rightrail: (slot) => `
      <div class="tshell tshell--rightrail">
        ${winBar}
        <div class="tshell__body tshell__body--rightrail">
          <main class="tshell__workspace">
            <div class="tshell__toolbar">
              <span class="tshell__skel" style="width:80px"></span>
              <span class="tshell__skel" style="width:50px;margin-left:auto"></span>
              <span class="tshell__skel" style="width:50px"></span>
            </div>
            <div class="tshell__doc">
              <span class="tshell__skel" style="width:60%;height:14px"></span>
              <span class="tshell__skel" style="width:85%"></span>
              <span class="tshell__skel" style="width:78%"></span>
              <span class="tshell__skel" style="width:90%"></span>
              <span class="tshell__skel" style="width:72%"></span>
              <span class="tshell__skel" style="width:55%"></span>
            </div>
          </main>
          <aside class="tshell__panel">
            <div class="tshell__panel-head">
              <span class="tshell__panel-title">Assistant</span>
              <span class="tshell__panel-close"></span>
            </div>
            <div class="tshell__slot">${slot}</div>
            <div class="tshell__panel-composer">Ask about this doc…</div>
          </aside>
        </div>
      </div>`,

    creative: (slot) => `
      <div class="tshell tshell--creative">
        ${winBar}
        <div class="tshell__body tshell__body--creative">
          <aside class="tshell__tools">
            <span class="tshell__tool"></span>
            <span class="tshell__tool"></span>
            <span class="tshell__tool tshell__tool--active"></span>
            <span class="tshell__tool"></span>
            <span class="tshell__tool"></span>
          </aside>
          <main class="tshell__canvas">
            <div class="tshell__asset">
              <div class="tshell__asset-frame">
                <span class="tshell__asset-label">AI-generated</span>
              </div>
              <div class="tshell__slot tshell__slot--under-asset">${slot}</div>
            </div>
          </main>
          <aside class="tshell__props">
            <div class="tshell__prop-head">Properties</div>
            <span class="tshell__skel" style="width:90%"></span>
            <span class="tshell__skel" style="width:70%"></span>
            <span class="tshell__skel" style="width:80%"></span>
          </aside>
        </div>
      </div>`,

    video: (slot) => `
      <div class="tshell tshell--video">
        ${winBar}
        <div class="tshell__body tshell__body--video">
          <div class="tshell__preview">
            <div class="tshell__preview-frame">
              <span class="tshell__play"></span>
            </div>
          </div>
          <div class="tshell__timeline">
            <div class="tshell__track">
              <div class="tshell__clip tshell__clip--user" style="width:18%"></div>
              <div class="tshell__clip tshell__clip--user" style="width:14%;margin-left:2%"></div>
              <div class="tshell__clip tshell__clip--ai" style="width:28%;margin-left:2%">
                <div class="tshell__slot tshell__slot--clip">${slot}</div>
              </div>
              <div class="tshell__clip tshell__clip--user" style="width:20%;margin-left:2%"></div>
            </div>
            <div class="tshell__track tshell__track--audio">
              <div class="tshell__clip tshell__clip--audio" style="width:64%"></div>
            </div>
          </div>
        </div>
      </div>`,

    code: (slot) => `
      <div class="tshell tshell--code">
        ${winBar}
        <div class="tshell__body tshell__body--code">
          <aside class="tshell__filetree">
            <span class="tshell__file"></span>
            <span class="tshell__file tshell__file--active"></span>
            <span class="tshell__file"></span>
            <span class="tshell__file"></span>
            <span class="tshell__file tshell__file--short"></span>
          </aside>
          <main class="tshell__editor">
            <div class="tshell__codeline"><span class="tshell__gutter">1</span><span class="tshell__tok tshell__tok--kw">function</span> <span class="tshell__tok tshell__tok--fn">renderMessage</span>(<span class="tshell__tok tshell__tok--arg">m</span>) {</div>
            <div class="tshell__codeline"><span class="tshell__gutter">2</span>  <span class="tshell__tok tshell__tok--kw">return</span> <span class="tshell__tok tshell__tok--str">\`&lt;div&gt;\${m.body}&lt;/div&gt;\`</span>;</div>
            <div class="tshell__codeline"><span class="tshell__gutter">3</span>}</div>
            <div class="tshell__codeline tshell__codeline--prompt">
              <span class="tshell__gutter">4</span>
              <div class="tshell__slot tshell__slot--prompt">${slot}</div>
            </div>
            <div class="tshell__codeline"><span class="tshell__gutter">5</span></div>
          </main>
        </div>
      </div>`,

    email: (slot) => `
      <div class="tshell tshell--email">
        ${winBar}
        <div class="tshell__body tshell__body--email">
          <aside class="tshell__inbox">
            <div class="tshell__inbox-row tshell__inbox-row--active"></div>
            <div class="tshell__inbox-row"></div>
            <div class="tshell__inbox-row"></div>
            <div class="tshell__inbox-row"></div>
          </aside>
          <main class="tshell__mail">
            <div class="tshell__mail-head">
              <span class="tshell__skel" style="width:50%;height:14px"></span>
              <span class="tshell__skel" style="width:28%;margin-top:8px"></span>
            </div>
            <div class="tshell__slot tshell__slot--draft">${slot}</div>
            <div class="tshell__mail-body">
              <span class="tshell__skel" style="width:92%"></span>
              <span class="tshell__skel" style="width:84%"></span>
              <span class="tshell__skel" style="width:60%"></span>
            </div>
            <div class="tshell__mail-actions">
              <span class="tshell__send">Send</span>
              <span class="tshell__skel" style="width:60px"></span>
            </div>
          </main>
        </div>
      </div>`
  };

  const renderTemplate = (templateId, slotHTML) => {
    const fn = templates[templateId];
    return fn ? fn(slotHTML) : `<div class="tshell tshell--unknown">Unknown template: ${esc(templateId)}</div>`;
  };

  // Small icons used on the placement pills
  const templateIcon = (id) => {
    const ico = {
      chat:      `<svg viewBox="0 0 24 24" fill="none"><path d="M21 12a8 8 0 0 1-8 8H7l-4 3v-4a8 8 0 1 1 18-7Z" stroke="currentColor" stroke-width="1.6" stroke-linejoin="round"/></svg>`,
      rightrail: `<svg viewBox="0 0 24 24" fill="none"><rect x="3" y="4" width="18" height="16" rx="2" stroke="currentColor" stroke-width="1.6"/><line x1="15" y1="4" x2="15" y2="20" stroke="currentColor" stroke-width="1.6"/></svg>`,
      creative:  `<svg viewBox="0 0 24 24" fill="none"><path d="M12 2a10 10 0 1 0 0 20c1.5 0 2-1 2-2v-1a2 2 0 0 1 2-2h2a3 3 0 0 0 3-3v-1A10 10 0 0 0 12 2Z" stroke="currentColor" stroke-width="1.6" stroke-linejoin="round"/><circle cx="7.5" cy="10" r="1.2" fill="currentColor"/><circle cx="12" cy="7" r="1.2" fill="currentColor"/><circle cx="16.5" cy="10" r="1.2" fill="currentColor"/></svg>`,
      video:     `<svg viewBox="0 0 24 24" fill="none"><rect x="2" y="5" width="20" height="14" rx="2" stroke="currentColor" stroke-width="1.6"/><polygon points="10,9 16,12 10,15" fill="currentColor"/></svg>`,
      code:      `<svg viewBox="0 0 24 24" fill="none"><polyline points="9 8 5 12 9 16" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"/><polyline points="15 8 19 12 15 16" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"/></svg>`,
      email:     `<svg viewBox="0 0 24 24" fill="none"><rect x="3" y="5" width="18" height="14" rx="2" stroke="currentColor" stroke-width="1.6"/><polyline points="3 7 12 13 21 7" stroke="currentColor" stroke-width="1.6" stroke-linejoin="round" fill="none"/></svg>`
    };
    return ico[id] || `<svg viewBox="0 0 24 24" fill="none"><rect x="4" y="4" width="16" height="16" rx="2" stroke="currentColor" stroke-width="1.6"/></svg>`;
  };

  // ───────────────────────────────────────────────────────
  // Flatten + lookup
  // ───────────────────────────────────────────────────────
  function flat() {
    const out = [];
    L.stages.forEach(s => s.subcats.forEach(sub => sub.patterns.forEach(p => out.push({ p, stage: s, sub }))));
    return out;
  }
  function getId() {
    return new URL(location.href).searchParams.get("id");
  }

  // ───────────────────────────────────────────────────────
  // Sidebar
  // ───────────────────────────────────────────────────────
  function renderSidebar(currentId, currentStageId) {
    const total = L.stages.reduce((n, s) => n + s.subcats.reduce((m, sub) => m + sub.patterns.length, 0), 0);
    const html = `
      <div class="sidebar__title">
        <h2>Library</h2>
        <small>${total} patterns</small>
      </div>
      <div class="tree">
        ${L.stages.map(s => `
          <div class="tree__stage" data-stage="${s.id}" aria-expanded="${s.id === currentStageId ? 'true' : 'false'}">
            <button class="tree__stage-head" type="button" data-toggle="${s.id}">
              <span class="name">${esc(s.label)}</span>
              <svg class="chev" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M9 6l6 6-6 6" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg>
            </button>
            <div class="tree__stage-body">
              ${s.subcats.map(sub => `
                <div class="tree__sub" data-sub="${sub.id}">
                  <div class="tree__sub-head">${esc(sub.title)}</div>
                  ${sub.patterns.map(p => `
                    <a class="tree__pattern ${p.id === currentId ? 'is-current' : ''}"
                       data-status="${p.placeholder ? 'scaffold' : 'full'}"
                       href="pattern.html?id=${encodeURIComponent(p.id)}">
                      ${esc(p.name)}<span class="badge-dot" aria-hidden="true"></span>
                    </a>
                  `).join("")}
                </div>
              `).join("")}
            </div>
          </div>
        `).join("")}
      </div>
      <div class="sidebar__extras">
        <a class="sidebar__extra" href="library.html">All patterns</a>
        <a class="sidebar__extra" href="index.html">Landing</a>
        <a class="sidebar__extra" href="https://www.intelligaia.com/contact" target="_blank" rel="noopener">Contact ↗</a>
      </div>
    `;
    $("#sidebar").innerHTML = html;
  }

  // ───────────────────────────────────────────────────────
  // Detail body — sentence-case section titles, no redundancy
  // ───────────────────────────────────────────────────────
  function renderDetail({ p, stage, sub }, neighbours) {
    const ph = p.placeholder === true;
    const v = visualFor(p)();

    const breadHTML = `
      <nav class="bread" aria-label="Breadcrumb">
        <a href="index.html">Home</a>
        <svg width="10" height="10" viewBox="0 0 24 24" fill="none"><path d="M9 6l6 6-6 6" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg>
        <a href="library.html#stage-${stage.id}">${esc(stage.label)}</a>
        <svg width="10" height="10" viewBox="0 0 24 24" fill="none"><path d="M9 6l6 6-6 6" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg>
        <span class="current">${esc(sub.title)}</span>
      </nav>
    `;

    // Hero: name + description first; metadata strip pushed down beneath them.
    // (No borrowed-framework references — this library is purely Intelligaia's system.)
    const metaStrip = `
      <div class="detail__meta-strip">
        ${p.value ? `<span class="meta-chip meta-chip--${p.value}">${valueLabel[p.value]}</span>` : ""}
        <span class="meta-chip ${ph ? 'meta-chip--scaffold' : 'meta-chip--full'}">${ph ? 'Scaffolded' : 'Documented'}</span>
      </div>
    `;
    const heroHTML = `
      <header class="detail__hero">
        <h1 class="detail__name">${esc(p.name)}</h1>
        <p class="detail__oneline">${esc(p.oneline)}</p>
        ${metaStrip}
      </header>
    `;

    const exampleHTML = `
      <section class="section-block" id="sec-example">
        <div class="section-block__head">
          <h2 class="section-block__title">Live preview</h2>
          <div class="section-block__lede">A small, inline preview of the canonical shape.</div>
        </div>
        <div class="example">${v}</div>
      </section>
    `;

    // ── Variants — full-preview cards. Each card renders the actual mock. ──
    const variants = Array.isArray(p.variants) ? p.variants : [];
    const variantsHTML = variants.length ? `
      <section class="section-block" id="sec-variants">
        <div class="section-block__head">
          <h2 class="section-block__title">Variants <span class="section-block__count">${variants.length}</span></h2>
          <div class="section-block__lede">The common shapes this pattern takes. Click any card to open the full preview.</div>
        </div>
        <div class="vcards">
          ${variants.map((vr, i) => `
            <button class="vcard" type="button" data-open="variant" data-index="${i}">
              <div class="vcard__stage">${vr.mock}</div>
              <div class="vcard__foot">
                <span class="vcard__name">${esc(vr.name)}</span>
                <span class="vcard__note">${esc(vr.note || "")}</span>
              </div>
            </button>
          `).join("")}
        </div>
      </section>
    ` : ph ? "" : `
      <section class="section-block" id="sec-variants">
        <div class="section-block__head">
          <h2 class="section-block__title">Variants</h2>
          <div class="section-block__lede">Common shapes this pattern can take.</div>
        </div>
        <p class="t-mid" style="font-size:15px;line-height:1.6;max-width:560px">
          Variant gallery is being authored for this pattern. The live preview above shows the canonical shape.
        </p>
      </section>
    `;

    // ── In-context — minimal independent carousel. Auto-rotating. ──
    const placements = Array.isArray(p.placements) ? p.placements : [];
    const placementsHTML = placements.length ? `
      <section class="section-block" id="sec-placements">
        <div class="section-block__head">
          <h2 class="section-block__title">In context <span class="section-block__count">${placements.length}</span></h2>
          <div class="section-block__lede">How this pattern fits into different AI-native tools. Click the preview to open it at full size.</div>
        </div>
        <div class="incx" data-incx>
          <div class="incx__label">
            <span class="incx__archetype" data-incx-archetype>—</span>
            <span class="incx__use" data-incx-use>—</span>
          </div>
          <button class="incx__stage" type="button" data-open="placement" aria-label="Open this preview at full size">
            <div class="incx__stage-inner" data-incx-stage></div>
          </button>
          <div class="incx__details">
            <span class="incx__variant-name" data-incx-tag>—</span>
            <span class="incx__note" data-incx-note>—</span>
          </div>
          <div class="incx__controls">
            <button class="incx__arrow" type="button" data-incx-prev aria-label="Previous">
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M15 6l-6 6 6 6" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>
            </button>
            <div class="incx__dots" data-incx-dots></div>
            <button class="incx__arrow" type="button" data-incx-next aria-label="Next">
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M9 6l6 6-6 6" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>
            </button>
          </div>
        </div>
      </section>
    ` : ph ? "" : `
      <section class="section-block" id="sec-placements">
        <div class="section-block__head">
          <h2 class="section-block__title">In context</h2>
          <div class="section-block__lede">Where this pattern lives inside AI-native tool archetypes.</div>
        </div>
        <p class="t-mid" style="font-size:15px;line-height:1.6;max-width:560px">
          In-context placements are being authored for this pattern.
        </p>
      </section>
    `;

    const placeholderHTML = `
      <section class="section-block" id="sec-status">
        <div class="section-block__head">
          <h2 class="section-block__title">Status</h2>
        </div>
        <p class="t-mid" style="font-size:16px;line-height:1.6;max-width:620px">
          This pattern is in the scaffold. Full documentation, live composition, and code snippet will be filled in as we deepen this stage. Browse
          <a href="library.html#stage-onboarding" style="border-bottom:1px solid var(--fg);color:var(--fg)">Onboarding</a>
          for examples of fully documented patterns.
        </p>
      </section>
    `;

    // Individual sections so we can re-order
    const composedHTML = `
      <section class="section-block" id="sec-composed">
        <div class="section-block__head">
          <h2 class="section-block__title">Composed from</h2>
          <div class="section-block__lede">Primitives from the design system that build this pattern.</div>
        </div>
        <div class="composed">
          ${(p.composed || []).map(c => `<span class="composed__chip">${esc(c)}</span>`).join("")}
        </div>
      </section>
    `;
    const codeHTML = `
      <section class="section-block" id="sec-code">
        <div class="section-block__head">
          <h2 class="section-block__title">Code shape</h2>
          <div class="section-block__lede">A canonical implementation skeleton — adapt to your framework.</div>
        </div>
        <pre class="code"><button class="code__copy" data-copy>Copy</button>${esc(p.code || "")}</pre>
      </section>
    `;
    const relatedHTML = `
      <section class="section-block" id="sec-related">
        <div class="section-block__head">
          <h2 class="section-block__title">Related patterns</h2>
          <div class="section-block__lede">Patterns commonly designed alongside this one.</div>
        </div>
        <div class="related">
          ${(p.related || []).map(id => {
            const r = flat().find(x => x.p.id === id);
            if (!r) return "";
            return `
              <a class="related__item" href="pattern.html?id=${encodeURIComponent(id)}">
                <div class="related__name">${esc(r.p.name)}</div>
                <div class="related__meta">${esc(r.stage.label)} · ${esc(r.sub.title)}</div>
              </a>`;
          }).join("")}
        </div>
      </section>
    `;
    // Four questions — moved to the bottom; stacked single-column.
    // Only rendered if at least one of the four fields has content (so scaffolded
    // patterns with rich variants/placements aren't padded with 4 empty rows).
    const hasQA = !!(p.what || p.why || p.when || p.how);
    const questionsHTML = hasQA ? `
      <section class="section-block" id="sec-questions">
        <div class="section-block__head">
          <h2 class="section-block__title">The four questions</h2>
          <div class="section-block__lede">Every pattern is documented against the same four prompts.</div>
        </div>
        <div class="qa-list">
          ${p.what ? `<div class="qa-row"><div class="qa-row__k">What it is</div><div class="qa-row__v">${esc(p.what)}</div></div>` : ""}
          ${p.why  ? `<div class="qa-row"><div class="qa-row__k">Why it matters</div><div class="qa-row__v">${esc(p.why)}</div></div>` : ""}
          ${p.when ? `<div class="qa-row"><div class="qa-row__k">When to use it</div><div class="qa-row__v">${esc(p.when)}</div></div>` : ""}
          ${p.how  ? `<div class="qa-row"><div class="qa-row__k">How to use it</div><div class="qa-row__v">${esc(p.how)}</div></div>` : ""}
        </div>
      </section>
    ` : "";
    // Only render composed/code if the data exists, to avoid empty sections on scaffolded patterns.
    const composedReal = (Array.isArray(p.composed) && p.composed.length) ? composedHTML : "";
    const codeReal     = (p.code && p.code.trim()) ? codeHTML : "";
    const relatedReal  = (Array.isArray(p.related) && p.related.length) ? relatedHTML : "";
    const fullHTML = composedReal + codeReal + relatedReal + questionsHTML;

    const navHTML = `
      <div class="detail__nav">
        ${neighbours.prev ? `
          <a href="pattern.html?id=${encodeURIComponent(neighbours.prev.p.id)}">
            <span class="dir">← Previous</span>
            <span class="name">${esc(neighbours.prev.p.name)}</span>
          </a>` : `<span></span>`}
        ${neighbours.next ? `
          <a class="next" href="pattern.html?id=${encodeURIComponent(neighbours.next.p.id)}">
            <span class="dir">Next →</span>
            <span class="name">${esc(neighbours.next.p.name)}</span>
          </a>` : `<span></span>`}
      </div>
    `;

    // If a pattern is technically scaffolded but has been enriched with variants or
    // placements, skip the "scaffold" status message — the page has real content now.
    const showScaffold = ph && !variants.length && !placements.length;
    $("#detail").innerHTML =
      breadHTML + heroHTML + exampleHTML + variantsHTML + placementsHTML + (showScaffold ? placeholderHTML : fullHTML) + navHTML;
  }

  // ───────────────────────────────────────────────────────
  // Right-side TOC ("On this page") + pattern metadata
  // ───────────────────────────────────────────────────────
  function renderTOC({ p, stage, sub }) {
    const ph = p.placeholder === true;
    const hasVariants   = Array.isArray(p.variants)   && p.variants.length   > 0;
    const hasPlacements = Array.isArray(p.placements) && p.placements.length > 0;
    const hasComposed   = Array.isArray(p.composed)   && p.composed.length   > 0;
    const hasCode       = !!(p.code && p.code.trim());
    const hasRelated    = Array.isArray(p.related)    && p.related.length    > 0;
    const hasQA         = !!(p.what || p.why || p.when || p.how);
    const showScaffold  = ph && !hasVariants && !hasPlacements;

    const items = showScaffold
      ? [{ id: "sec-example", label: "Live preview" }, { id: "sec-status", label: "Status" }]
      : [
          { id: "sec-example",    label: "Live preview" },
          hasVariants   ? { id: "sec-variants",   label: "Variants" }            : null,
          hasPlacements ? { id: "sec-placements", label: "In context" }          : null,
          hasComposed   ? { id: "sec-composed",   label: "Composed from" }       : null,
          hasCode       ? { id: "sec-code",       label: "Code shape" }          : null,
          hasRelated    ? { id: "sec-related",    label: "Related patterns" }    : null,
          hasQA         ? { id: "sec-questions",  label: "The four questions" }  : null
        ].filter(Boolean);

    const html = `
      <div class="toc__title">On this page</div>
      <nav class="toc__list">
        ${items.map(i => `<a class="toc__link" href="#${i.id}">${i.label}</a>`).join("")}
      </nav>
      <div class="toc__meta">
        <div class="toc__meta-row"><span class="toc__meta-k">Stage</span><span class="toc__meta-v">${esc(stage.label)}</span></div>
        <div class="toc__meta-row"><span class="toc__meta-k">Category</span><span class="toc__meta-v">${esc(sub.title)}</span></div>
        ${p.value ? `<div class="toc__meta-row"><span class="toc__meta-k">User value</span><span class="toc__meta-v">${valueLabel[p.value]}</span></div>` : ""}
      </div>
    `;
    $("#toc").innerHTML = html;
  }

  function wireTOC() {
    const links = $$(".toc__link");
    const sections = links.map(l => document.querySelector(l.getAttribute("href"))).filter(Boolean);
    if (!sections.length) return;

    function update() {
      const top = 80;
      let active = sections[0];
      for (const s of sections) if (s.getBoundingClientRect().top - top < 0) active = s;
      links.forEach(l => l.classList.toggle("is-active", l.getAttribute("href") === "#" + active.id));
    }
    update();
    window.addEventListener("scroll", update, { passive: true });
  }

  // ───────────────────────────────────────────────────────
  // Inline In-context carousel — one big tool shell on the page
  // ───────────────────────────────────────────────────────
  const incxState = { items: [], index: 0, pattern: null, timer: null, pauseTimer: null };
  const AUTO_INTERVAL = 6000;       // advance every 6s
  const POST_INTERACT_PAUSE = 8000; // pause 8s after manual nav

  function initIncx(pattern) {
    const items = Array.isArray(pattern.placements) ? pattern.placements : [];
    if (!items.length) return;
    incxState.items = items;
    incxState.pattern = pattern;
    incxState.index = 0;
    renderIncx();
    // build dots
    const dotsEl = $("[data-incx-dots]");
    if (dotsEl) {
      dotsEl.innerHTML = items.map((_, i) => `<button class="incx__dot ${i === 0 ? 'is-active' : ''}" type="button" data-incx-dot="${i}" aria-label="Go to ${i + 1}"></button>`).join("");
    }
    // auto-rotate + hover pause
    startAuto();
    const root = $("[data-incx]");
    if (root) {
      root.addEventListener("mouseenter", stopAuto);
      root.addEventListener("mouseleave", startAuto);
    }
  }

  function startAuto() {
    stopAuto();
    if (incxState.items.length <= 1) return;
    // Also bail out if the lightbox is open
    const lbx = $("#lightbox");
    if (lbx && !lbx.hasAttribute("hidden")) return;
    incxState.timer = setInterval(() => {
      incxState.index = (incxState.index + 1) % incxState.items.length;
      renderIncx();
    }, AUTO_INTERVAL);
  }
  function stopAuto() {
    if (incxState.timer) { clearInterval(incxState.timer); incxState.timer = null; }
  }
  function pauseAutoTemporarily() {
    stopAuto();
    if (incxState.pauseTimer) clearTimeout(incxState.pauseTimer);
    incxState.pauseTimer = setTimeout(() => {
      // Only resume if cursor is not currently over the carousel
      const root = $("[data-incx]");
      if (!root || !root.matches(":hover")) startAuto();
    }, POST_INTERACT_PAUSE);
  }

  function renderIncx() {
    const { items, index, pattern } = incxState;
    if (!items.length) return;
    const pl = items[index];
    const meta = templateMeta[pl.template] || { label: pl.template, use: "" };
    const vr = (pattern.variants || []).find(x => x.id === pl.variantId);
    const slot = vr ? `<div class="placement__variant-inner">${vr.mock}</div>` : `<div class="t-muted">Variant not found</div>`;

    const archEl   = $("[data-incx-archetype]");
    const useEl    = $("[data-incx-use]");
    const tagEl    = $("[data-incx-tag]");
    const stageEl  = $("[data-incx-stage]");
    const noteEl   = $("[data-incx-note]");

    if (archEl)  archEl.textContent = meta.label;
    if (useEl)   useEl.textContent  = meta.use || "";
    if (tagEl)   tagEl.textContent  = vr ? vr.name : "";
    if (stageEl) stageEl.innerHTML  = renderTemplate(pl.template, slot);
    if (noteEl)  noteEl.textContent = pl.note || "";

    $$(".incx__dot").forEach((d, i) => d.classList.toggle("is-active", i === index));
  }

  function navIncx(delta) {
    const { items, index } = incxState;
    if (!items.length) return;
    incxState.index = (index + delta + items.length) % items.length;
    renderIncx();
  }
  function jumpIncx(toIndex) {
    if (toIndex === incxState.index) return;
    incxState.index = toIndex;
    renderIncx();
  }

  // ───────────────────────────────────────────────────────
  // Lightbox carousel — opens variants and placements at full size
  // ───────────────────────────────────────────────────────
  const lightboxState = { type: null, items: [], index: 0, pattern: null };

  function buildLightbox() {
    if ($("#lightbox")) return;
    const node = document.createElement("div");
    node.id = "lightbox";
    node.className = "lightbox";
    node.setAttribute("hidden", "");
    node.setAttribute("role", "dialog");
    node.setAttribute("aria-modal", "true");
    node.innerHTML = `
      <div class="lightbox__backdrop" data-lbx-close></div>
      <div class="lightbox__panel" role="document">
        <header class="lightbox__head">
          <div class="lightbox__heads">
            <div class="lightbox__eyebrow" id="lbx-eyebrow">Variant</div>
            <h3 class="lightbox__title" id="lbx-title">—</h3>
            <div class="lightbox__sub" id="lbx-sub"></div>
          </div>
          <div class="lightbox__head-actions">
            <span class="lightbox__counter" id="lbx-counter">1 / 1</span>
            <button class="lightbox__close" type="button" data-lbx-close aria-label="Close preview">
              <svg width="18" height="18" viewBox="0 0 24 24" fill="none"><path d="M6 6l12 12M6 18L18 6" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg>
            </button>
          </div>
        </header>
        <div class="lightbox__stage" id="lbx-stage"></div>
        <p class="lightbox__note" id="lbx-note"></p>
        <div class="lightbox__nav">
          <button class="lightbox__arrow" type="button" data-lbx-prev aria-label="Previous">
            <svg width="18" height="18" viewBox="0 0 24 24" fill="none"><path d="M15 6l-6 6 6 6" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>
          </button>
          <div class="lightbox__dots" id="lbx-dots"></div>
          <button class="lightbox__arrow" type="button" data-lbx-next aria-label="Next">
            <svg width="18" height="18" viewBox="0 0 24 24" fill="none"><path d="M9 6l6 6-6 6" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>
          </button>
        </div>
      </div>
    `;
    document.body.appendChild(node);
  }

  function openLightbox(type, index, pattern) {
    const variants   = Array.isArray(pattern.variants)   ? pattern.variants   : [];
    const placements = Array.isArray(pattern.placements) ? pattern.placements : [];
    const items = type === "variant" ? variants : placements;
    if (!items.length) return;

    lightboxState.type = type;
    lightboxState.items = items;
    lightboxState.index = Math.max(0, Math.min(index, items.length - 1));
    lightboxState.pattern = pattern;

    renderLightbox();
    const lbx = $("#lightbox");
    lbx.removeAttribute("hidden");
    document.body.classList.add("is-lbx-open");
    requestAnimationFrame(() => lbx.classList.add("is-open"));
    stopAuto(); // freeze inline carousel while modal is open
  }

  function closeLightbox() {
    const lbx = $("#lightbox");
    if (!lbx || lbx.hasAttribute("hidden")) return;
    lbx.classList.remove("is-open");
    document.body.classList.remove("is-lbx-open");
    setTimeout(() => lbx.setAttribute("hidden", ""), 200);
    // Resume only if cursor isn't hovering the inline carousel
    const root = $("[data-incx]");
    if (!root || !root.matches(":hover")) startAuto();
  }

  function navLightbox(delta) {
    const { items, index } = lightboxState;
    if (!items.length) return;
    lightboxState.index = (index + delta + items.length) % items.length;
    renderLightbox();
  }

  function jumpLightbox(toIndex) {
    if (toIndex === lightboxState.index) return;
    lightboxState.index = toIndex;
    renderLightbox();
  }

  function renderLightbox() {
    const { type, items, index, pattern } = lightboxState;
    if (!items.length) return;
    const it = items[index];
    const isVariant = type === "variant";

    let stageHTML, title, sub, note, eyebrow;
    if (isVariant) {
      eyebrow = "Variant";
      title = it.name;
      sub = "";
      note = it.note || "";
      stageHTML = `<div class="lbx-mock">${it.mock}</div>`;
    } else {
      const meta = templateMeta[it.template] || { label: it.template, use: "" };
      const vr = (pattern.variants || []).find(x => x.id === it.variantId);
      const slot = vr ? `<div class="placement__variant-inner">${vr.mock}</div>` : `<div class="t-muted">Variant not found</div>`;
      eyebrow = meta.use || "In context";
      title = meta.label;
      sub = vr ? `Showing: ${vr.name}` : "";
      note = it.note || "";
      stageHTML = renderTemplate(it.template, slot);
    }

    $("#lbx-eyebrow").textContent = eyebrow;
    $("#lbx-title").textContent = title;
    $("#lbx-sub").textContent = sub;
    $("#lbx-counter").textContent = `${index + 1} / ${items.length}`;
    $("#lbx-note").textContent = note;
    $("#lbx-stage").innerHTML = stageHTML;

    const dots = items.map((_, i) => `<button class="lightbox__dot ${i === index ? 'is-active' : ''}" type="button" data-lbx-dot="${i}" aria-label="Go to ${i + 1}"></button>`).join("");
    $("#lbx-dots").innerHTML = dots;
  }

  // ───────────────────────────────────────────────────────
  // Behaviours
  // ───────────────────────────────────────────────────────
  function wire(pattern) {
    document.addEventListener("click", (e) => {
      // Sidebar stage expand/collapse
      const t = e.target.closest("[data-toggle]");
      if (t) {
        const stageEl = t.parentElement;
        const open = stageEl.getAttribute("aria-expanded") === "true";
        stageEl.setAttribute("aria-expanded", open ? "false" : "true");
        return;
      }
      // Copy code
      const copyBtn = e.target.closest("[data-copy]");
      if (copyBtn) {
        const pre = copyBtn.parentElement;
        const text = pre.innerText.replace(/^Copy\n?/, "");
        navigator.clipboard.writeText(text).then(() => {
          copyBtn.textContent = "Copied";
          setTimeout(() => copyBtn.textContent = "Copy", 1400);
        }).catch(() => {});
      }
      // Inline carousel controls
      if (e.target.closest("[data-incx-prev]")) { navIncx(-1); pauseAutoTemporarily(); return; }
      if (e.target.closest("[data-incx-next]")) { navIncx(+1); pauseAutoTemporarily(); return; }
      const idot = e.target.closest("[data-incx-dot]");
      if (idot) { jumpIncx(parseInt(idot.getAttribute("data-incx-dot"), 10) || 0); pauseAutoTemporarily(); return; }

      // Open lightbox from a card/pill/inline-carousel
      const openBtn = e.target.closest("[data-open]");
      if (openBtn) {
        const type = openBtn.getAttribute("data-open");
        // If the trigger has data-index, use it (variant cards); otherwise default to the
        // current inline carousel index (so "Open full size" matches what's on screen).
        const explicitIdx = openBtn.getAttribute("data-index");
        const idx = explicitIdx !== null ? parseInt(explicitIdx, 10) || 0 : (type === "placement" ? incxState.index : 0);
        openLightbox(type, idx, pattern);
        return;
      }
      // Lightbox controls
      if (e.target.closest("[data-lbx-close]")) { closeLightbox(); return; }
      if (e.target.closest("[data-lbx-prev]"))  { navLightbox(-1); return; }
      if (e.target.closest("[data-lbx-next]"))  { navLightbox(+1); return; }
      const dot = e.target.closest("[data-lbx-dot]");
      if (dot) { jumpLightbox(parseInt(dot.getAttribute("data-lbx-dot"), 10) || 0); return; }
    });

    document.addEventListener("keydown", (e) => {
      const lbx = $("#lightbox");
      if (!lbx || lbx.hasAttribute("hidden")) return;
      if (e.key === "Escape")      closeLightbox();
      else if (e.key === "ArrowLeft")  navLightbox(-1);
      else if (e.key === "ArrowRight") navLightbox(+1);
    });
  }

  function boot() {
    const all = flat();
    // Default to "disclosure" if no ?id= is present (so the file works
    // when double-clicked from Finder, no server required).
    const id = getId() || "disclosure";
    let idx = all.findIndex(x => x.p.id === id);

    // If even the fallback isn't found, land on the first pattern in the catalog.
    if (idx < 0) idx = 0;
    if (idx < 0) { location.href = "library.html"; return; }

    const current = all[idx];
    const neighbours = {
      prev: idx > 0 ? all[idx - 1] : null,
      next: idx < all.length - 1 ? all[idx + 1] : null
    };

    document.title = `${current.p.name} — Intelligaia AI UX Pattern Library`;

    renderSidebar(current.p.id, current.stage.id);
    renderDetail(current, neighbours);
    renderTOC(current);
    buildLightbox();
    initIncx(current.p);
    wire(current.p);
    wireTOC();

    const s = document.createElement("style");
    s.textContent = `
      @keyframes pulse { 0%, 80%, 100% { opacity: 0.3; } 40% { opacity: 1; } }
      @keyframes blink { 0%, 49% { opacity: 1; } 50%, 100% { opacity: 0; } }
      @keyframes pulse-ring {
        0%   { box-shadow: 0 0 0 0 var(--accent); }
        70%  { box-shadow: 0 0 0 10px rgba(217, 119, 6, 0); }
        100% { box-shadow: 0 0 0 0 rgba(217, 119, 6, 0); }
      }
    `;
    document.head.appendChild(s);

    setTimeout(() => {
      const cur = $(".tree__pattern.is-current");
      if (cur) cur.scrollIntoView({ block: "center", behavior: "instant" });
      window.scrollTo({ top: 0, behavior: "instant" });
    }, 0);
  }

  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", boot);
  else boot();
})();
